# Generated by Django 6.0.3 on 2026-09-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OliveBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=20, unique=True)),
                ('producer', models.CharField(max_length=100)),
                ('olive_type', models.CharField(max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Kabul Edildi', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_code', models.CharField(max_length=10, unique=True)),
                ('capacity_liters', models.IntegerField()),
                ('current_liters', models.IntegerField(default=0)),
                ('oil_type', models.CharField(max_length=100)),
            ],
        ),
    ]
