# Generated by Django 6.0.3 on 2026-09-14 10:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSortingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer', models.CharField(max_length=100)),
                ('sequence_no', models.IntegerField()),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OlivePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olive_type', models.CharField(max_length=50, unique=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SieveStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('responsible', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('commission_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSortingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olive_type', models.CharField(max_length=50)),
                ('size_11', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('size_12', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('size_13', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('size_14', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('size_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('size_16', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('size_17', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('oil_release', models.CharField(choices=[('11-12', '11-12'), ('other', 'Diğer'), ('none', 'Yok')], default='none', max_length=20)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.customersortingrecord')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='customersortingrecord',
            name='sieve_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.sievestation'),
        ),
    ]
