# Generated by Django 6.0.3 on 2026-09-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customersortingrecord_oliveprice_sievestation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sievestation',
            name='commission_basis',
            field=models.CharField(choices=[('kg', 'TL/KG'), ('amount', 'Toplam Tutar')], default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='sievestation',
            name='commission_scope',
            field=models.CharField(choices=[('total_weight', 'Toplam KG'), ('net_weight', 'Net KG'), ('oil_weight', 'Yağlık KG'), ('sales_amount', 'Satış Tutarı')], default='total_weight', max_length=30),
        ),
        migrations.AddField(
            model_name='sievestation',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], default='Aktif', max_length=20),
        ),
        migrations.AddField(
            model_name='sievestation',
            name='work_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customersortingitem',
            name='oil_release',
            field=models.CharField(choices=[('11-12', '11-12'), ('13-17', '13-17'), ('all', 'Tümü'), ('none', 'Yok')], default='none', max_length=20),
        ),
    ]
