# Generated by Django 6.0.3 on 2026-09-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersortingrecord',
            name='whatsapp_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customersortingrecord',
            name='whatsapp_message_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customersortingrecord',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersortingrecord',
            name='whatsapp_status',
            field=models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Gönderildi', 'Gönderildi'), ('Gönderilemedi', 'Gönderilemedi')], default='Bekliyor', max_length=20),
        ),
    ]
