# Generated by Django 6.0.3 on 2026-09-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customersortingrecord_whatsapp_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersortingitem',
            name='oil_release',
            field=models.CharField(choices=[('11-12', '11-12'), ('13-17', '13-17'), ('all', 'Tümü'), ('none', 'Yok')], default='none', max_length=50),
        ),
    ]
