# Generated by Django 6.0.3 on 2026-09-15 08:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_customersortingitem_oil_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsiblePersonPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to='core.responsibleperson')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
