# Generated by Django 6.0.3 on 2026-09-15 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_responsiblepersonpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersortingrecord',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorting_records', to='core.responsibleperson'),
        ),
    ]
