# Generated by Django 6.0.3 on 2026-09-17 14:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merchantparty_salesrecord_salespayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olive_type', models.CharField(max_length=50, unique=True)),
                ('size_11', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('size_12', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('size_13', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('size_14', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('size_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('size_16', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('size_17', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olive_type', models.CharField(max_length=50)),
                ('size', models.PositiveSmallIntegerField()),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.salesrecord')),
            ],
        ),
    ]
