# Generated by Django 6.0.3 on 2026-09-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_salesprice_salesitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='oil_release',
            field=models.BooleanField(default=False),
        ),
    ]
