# Generated by Django 6.0.3 on 2026-09-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_driver_salesrecord_driver_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['plate']},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
    ]
