# Generated by Django 6.0.3 on 2026-09-19 10:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_vehicle_options_remove_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Yuklemede', 'Yüklemede'), ('Yolda', 'Yolda'), ('Vardi', 'Vardı')], default='Yuklemede', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='core.driver')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='core.salesrecord')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='core.vehicle')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('olive', 'Zeytin'), ('oil', 'Zeytinyağı')], max_length=10)),
                ('olive_type', models.CharField(blank=True, default='', max_length=50)),
                ('size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shipment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
