# Generated by Django 6.0.3 on 2026-09-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_shipment_shipmentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='is_loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Yuklemede', 'Yüklemede'), ('Yolda', 'Yolda'), ('AdreseUlasti', 'Teslimat adresine ulaştı'), ('Vardi', 'Teslimat adresine ulaştı')], default='Yuklemede', max_length=20),
        ),
    ]
